# Generated by Django 3.2.7 on 2021-10-09 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('fields', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default=None, max_length=255, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('in_stock', models.BooleanField()),
                ('price', models.BigIntegerField(default=None, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announce_type', to_field='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone')),
            ],
        ),
    ]
