# Generated by Django 3.2.7 on 2021-10-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Москва', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.city', to_field='city')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default=None, max_length=255, null=True)),
                ('house', models.IntegerField(default=None, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.city', to_field='city')),
                ('metro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality.metro', to_field='station')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.BigIntegerField(unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('subscribed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality.location')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality.role', to_field='role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
