name: Test docker-compose

on:
  push:
    branches:
      - dev

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run docker-compose
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/checkout@v3
      # Use the output from the `hello` step
      - name: Get the output time
        run: docker-compose build
